"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-01 01:43:35.718138
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_charges_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('webhook_events',
    sa.Column('stripe_event_id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stripe_event_id')
    )
    op.create_table('ingredients',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'key', name='uq_ingredient_key')
    )
    op.create_index(op.f('ix_ingredients_venue_id'), 'ingredients', ['venue_id'], unique=False)
    op.create_table('menu_sections',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('schedule_key', sa.String(length=80), nullable=True),
    sa.Column('opens_at', sa.String(length=16), nullable=True),
    sa.Column('hidden_when_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'key', name='uq_section_key')
    )
    op.create_index(op.f('ix_menu_sections_venue_id'), 'menu_sections', ['venue_id'], unique=False)
    op.create_table('menu_sources',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('label', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_on', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'key', name='uq_source_key')
    )
    op.create_index(op.f('ix_menu_sources_venue_id'), 'menu_sources', ['venue_id'], unique=False)
    op.create_table('menu_warnings',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('text', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'key', name='uq_warning_key')
    )
    op.create_index(op.f('ix_menu_warnings_venue_id'), 'menu_warnings', ['venue_id'], unique=False)
    op.create_table('schedules',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'key', name='uq_schedule_key')
    )
    op.create_index(op.f('ix_schedules_venue_id'), 'schedules', ['venue_id'], unique=False)
    op.create_table('tables',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('token_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('venue_id', 'label', name='uq_table_label')
    )
    op.create_index(op.f('ix_tables_venue_id'), 'tables', ['venue_id'], unique=False)
    op.create_table('users',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_failed_attempts', sa.Integer(), nullable=False),
    sa.Column('pin_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'email', name='uq_user_email')
    )
    op.create_index(op.f('ix_users_venue_id'), 'users', ['venue_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=120), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_venue_id'), 'audit_log', ['venue_id'], unique=False)
    op.create_table('devices',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('device_token', sa.String(length=64), nullable=False),
    sa.Column('registered_by', sa.UUID(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    op.create_index(op.f('ix_devices_venue_id'), 'devices', ['venue_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('schedule_key', sa.String(length=80), nullable=True),
    sa.Column('opens_at', sa.String(length=16), nullable=True),
    sa.Column('hidden_when_closed', sa.Boolean(), nullable=False),
    sa.Column('orderable', sa.Boolean(), nullable=False),
    sa.Column('orderable_reason', sa.String(length=40), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allergens_a', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allergens_m', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allergens_r', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['menu_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'key', name='uq_menu_item_key')
    )
    op.create_index(op.f('ix_menu_items_venue_id'), 'menu_items', ['venue_id'], unique=False)
    op.create_table('orders',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_pence', sa.Integer(), nullable=False),
    sa.Column('client_token', sa.String(length=80), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=80), nullable=True),
    sa.Column('checkout_session_id', sa.String(length=120), nullable=True),
    sa.Column('refunded_pence', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('served_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'client_token', name='uq_order_client_token')
    )
    op.create_index(op.f('ix_orders_payment_intent_id'), 'orders', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_venue_id'), 'orders', ['venue_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_pence', sa.Integer(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('station_snapshot', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('sessions',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_venue_id'), 'sessions', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_venue_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_venue_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_intent_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_menu_items_venue_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_devices_venue_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_audit_log_venue_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_venue_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tables_venue_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_schedules_venue_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_menu_warnings_venue_id'), table_name='menu_warnings')
    op.drop_table('menu_warnings')
    op.drop_index(op.f('ix_menu_sources_venue_id'), table_name='menu_sources')
    op.drop_table('menu_sources')
    op.drop_index(op.f('ix_menu_sections_venue_id'), table_name='menu_sections')
    op.drop_table('menu_sections')
    op.drop_index(op.f('ix_ingredients_venue_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_table('webhook_events')
    op.drop_table('venues')
    # ### end Alembic commands ###
